apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::813690942448:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-PC5QCP54EV5G
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::813690942448:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-16T21:07:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1792"
  uid: 81d7955e-f97b-4880-ad34-b797d6559acf
